import { SearchEngine, SortEngine } from ".";

describe("Sort engine: ", () => {
  it("Sort by RATE works as expected", () => {
    expect(
      SortEngine.rate([
        {
          placeId: 31,
          rateReal: 0.5
        },
        {
          placeId: 32,
          rateReal: 0.1
        },
        {
          placeId: 33,
          rateReal: 1.0
        },
        {
          placeId: 34,
          rateReal: 0.2
        }
      ])
    ).toEqual([
      {
        placeId: 32,
        rateReal: 0.1
      },
      {
        placeId: 34,
        rateReal: 0.2
      },
      {
        placeId: 31,
        rateReal: 0.5
      },
      {
        placeId: 33,
        rateReal: 1.0
      }
    ]);
  });
  it("Sort by DISTANCE works as expected", () => {
    expect(
      SortEngine.distance(
        [
          {
            placeId: 31,
            latitude: 0.5,
            longitude: 0.8
          },
          {
            placeId: 32,
            latitude: 0.5,
            longitude: 0.7
          },
          {
            placeId: 33,
            latitude: 0.5,
            longitude: 0.6
          }
        ],
        {
          latitude: 0.5,
          longitude: 0.5
        }
      )
    ).toEqual([
      {
        distance: 11.119069268139768,
        placeId: 33,
        latitude: 0.5,
        longitude: 0.6
      },
      {
        distance: 22.238138535634697,
        placeId: 32,
        latitude: 0.5,
        longitude: 0.7
      },
      {
        distance: 33.35720780183998,
        placeId: 31,
        latitude: 0.5,
        longitude: 0.8
      }
    ]);
  });
});

describe("Search engine: ", () => {
  it("Search by AUTOCOMPLETE works as expected", () => {
    expect(
      SearchEngine.autocomplete(
        [
          {
            altura: "sin número",
            aprobado: true,
            barrio_localidad: "Grand Bourg",
            calle: "Cabo Sosa",
            comentarios_distrib: "",
            comentarios_ile: "",
            comentarios_infectologia: "",
            comentarios_mac: "",
            comentarios_vac: "",
            condones: true,
            cruce: "El Callao",
            dc: false,
            establecimiento: "11 De Febrero",
            formattedAddress: "",
            friendly_condones: false,
            friendly_dc: false,
            friendly_ile: false,
            friendly_infectologia: false,
            friendly_mac: false,
            friendly_prueba: false,
            friendly_ssr: false,
            friendly_vacunatorios: false,
            habilitado: false,
            horario_distrib: "De 8 a 18hs",
            horario_ile: "",
            horario_infectologia: "",
            horario_mac: "",
            horario_testeo: "",
            horario_vac: "",
            ile: false,
            latitude: -34.486068,
            longitude: -58.7250438,
            mac: false,
            mail_distrib: "",
            mail_ile: "",
            mail_infectologia: "",
            mail_mac: "",
            mail_testeo: "",
            mail_vac: "",
            observacion: "",
            observaciones_testeo: "",
            pais: "",
            partido_comuna: "",
            piso_dpto: "",
            placeId: -1,
            provincia_region: "",
            prueba: false,
            responsable_distrib: "Caino Margarita",
            responsable_ile: "",
            responsable_infectologia: "",
            responsable_mac: "",
            responsable_testeo: "",
            responsable_vac: "",
            ssr: false,
            tel_distrib: "(02320) 480546",
            tel_ile: "",
            tel_infectologia: "",
            tel_mac: "",
            tel_testeo: "",
            tel_vac: "",
            tipo: "",
            ubicacion_distrib: "",
            ubicacion_ile: "",
            ubicacion_infectologia: "",
            ubicacion_mac: "",
            ubicacion_testeo: "",
            ubicacion_vac: "",
            web_distrib: "",
            web_ile: "",
            web_infectologia: "",
            web_mac: "",
            web_testeo: "",
            web_vac: ""
          },
          {
            altura: "sin número",
            aprobado: true,
            barrio_localidad: "Grand Bourg",
            calle: "Cabo Sosa",
            comentarios_distrib: "",
            comentarios_ile: "",
            comentarios_infectologia: "",
            comentarios_mac: "",
            comentarios_vac: "",
            condones: true,
            cruce: "El Callao",
            dc: false,
            establecimiento: "11 De Febrero",
            formattedAddress: "",
            friendly_condones: false,
            friendly_dc: false,
            friendly_ile: false,
            friendly_infectologia: false,
            friendly_mac: false,
            friendly_prueba: false,
            friendly_ssr: false,
            friendly_vacunatorios: false,
            habilitado: false,
            horario_distrib: "De 8 a 18hs",
            horario_ile: "",
            horario_infectologia: "",
            horario_mac: "",
            horario_testeo: "",
            horario_vac: "",
            ile: false,
            latitude: 5,
            longitude: 10,
            mac: false,
            mail_distrib: "",
            mail_ile: "",
            mail_infectologia: "",
            mail_mac: "",
            mail_testeo: "",
            mail_vac: "",
            observacion: "",
            observaciones_testeo: "",
            pais: "",
            partido_comuna: "",
            piso_dpto: "",
            placeId: -1,
            provincia_region: "",
            prueba: false,
            responsable_distrib: "Caino Margarita",
            responsable_ile: "",
            responsable_infectologia: "",
            responsable_mac: "",
            responsable_testeo: "",
            responsable_vac: "",
            ssr: false,
            tel_distrib: "(02320) 480546",
            tel_ile: "",
            tel_infectologia: "",
            tel_mac: "",
            tel_testeo: "",
            tel_vac: "",
            tipo: "",
            ubicacion_distrib: "",
            ubicacion_ile: "",
            ubicacion_infectologia: "",
            ubicacion_mac: "",
            ubicacion_testeo: "",
            ubicacion_vac: "",
            web_distrib: "",
            web_ile: "",
            web_infectologia: "",
            web_mac: "",
            web_testeo: "",
            web_vac: ""
          }
        ],
        {
          latitude: -34.486068,
          longitude: -58.7250438
        }
      )
    ).toEqual([
      {
        altura: "sin número",
        aprobado: true,
        barrio_localidad: "Grand Bourg",
        calle: "Cabo Sosa",
        comentarios_distrib: "",
        comentarios_ile: "",
        comentarios_infectologia: "",
        comentarios_mac: "",
        comentarios_vac: "",
        condones: true,
        cruce: "El Callao",
        dc: false,
        establecimiento: "11 De Febrero",
        formattedAddress: "",
        friendly_condones: false,
        friendly_dc: false,
        friendly_ile: false,
        friendly_infectologia: false,
        friendly_mac: false,
        friendly_prueba: false,
        friendly_ssr: false,
        friendly_vacunatorios: false,
        habilitado: false,
        horario_distrib: "De 8 a 18hs",
        horario_ile: "",
        horario_infectologia: "",
        horario_mac: "",
        horario_testeo: "",
        horario_vac: "",
        ile: false,
        latitude: -34.486068,
        longitude: -58.7250438,
        mac: false,
        mail_distrib: "",
        mail_ile: "",
        mail_infectologia: "",
        mail_mac: "",
        mail_testeo: "",
        mail_vac: "",
        observacion: "",
        observaciones_testeo: "",
        pais: "",
        partido_comuna: "",
        piso_dpto: "",
        placeId: -1,
        provincia_region: "",
        prueba: false,
        responsable_distrib: "Caino Margarita",
        responsable_ile: "",
        responsable_infectologia: "",
        responsable_mac: "",
        responsable_testeo: "",
        responsable_vac: "",
        ssr: false,
        tel_distrib: "(02320) 480546",
        tel_ile: "",
        tel_infectologia: "",
        tel_mac: "",
        tel_testeo: "",
        tel_vac: "",
        tipo: "",
        ubicacion_distrib: "",
        ubicacion_ile: "",
        ubicacion_infectologia: "",
        ubicacion_mac: "",
        ubicacion_testeo: "",
        ubicacion_vac: "",
        web_distrib: "",
        web_ile: "",
        web_infectologia: "",
        web_mac: "",
        web_testeo: "",
        web_vac: ""
      }
    ]);
  });
  it("Search by GEOLOCATION works as expected", () => {});
  it("Search by TEEN works as expected", () => {
    expect(
      SearchEngine.teen(
        [
          {
            altura: "sin número",
            aprobado: true,
            barrio_localidad: "Grand Bourg",
            calle: "Cabo Sosa",
            comentarios_distrib: "",
            comentarios_ile: "",
            comentarios_infectologia: "",
            comentarios_mac: "",
            comentarios_vac: "",
            condones: true,
            cruce: "El Callao",
            dc: false,
            establecimiento: "11 De Febrero",
            formattedAddress: "",
            friendly_condones: true,
            friendly_dc: false,
            friendly_ile: false,
            friendly_infectologia: false,
            friendly_mac: false,
            friendly_prueba: false,
            friendly_ssr: false,
            friendly_vacunatorios: false,
            habilitado: false,
            horario_distrib: "De 8 a 18hs",
            horario_ile: "",
            horario_infectologia: "",
            horario_mac: "",
            horario_testeo: "",
            horario_vac: "",
            ile: false,
            latitude: -34.486068,
            longitude: -58.7250438,
            mac: false,
            mail_distrib: "",
            mail_ile: "",
            mail_infectologia: "",
            mail_mac: "",
            mail_testeo: "",
            mail_vac: "",
            observacion: "",
            observaciones_testeo: "",
            pais: "",
            partido_comuna: "",
            piso_dpto: "",
            placeId: -1,
            provincia_region: "",
            prueba: false,
            responsable_distrib: "Caino Margarita",
            responsable_ile: "",
            responsable_infectologia: "",
            responsable_mac: "",
            responsable_testeo: "",
            responsable_vac: "",
            ssr: false,
            tel_distrib: "(02320) 480546",
            tel_ile: "",
            tel_infectologia: "",
            tel_mac: "",
            tel_testeo: "",
            tel_vac: "",
            tipo: "",
            ubicacion_distrib: "",
            ubicacion_ile: "",
            ubicacion_infectologia: "",
            ubicacion_mac: "",
            ubicacion_testeo: "",
            ubicacion_vac: "",
            web_distrib: "",
            web_ile: "",
            web_infectologia: "",
            web_mac: "",
            web_testeo: "",
            web_vac: ""
          },
          {
            altura: "sin número",
            aprobado: true,
            barrio_localidad: "Grand Bourg",
            calle: "Cabo Sosa",
            comentarios_distrib: "",
            comentarios_ile: "",
            comentarios_infectologia: "",
            comentarios_mac: "",
            comentarios_vac: "",
            condones: true,
            cruce: "El Callao",
            dc: false,
            establecimiento: "11 De Febrero",
            formattedAddress: "",
            friendly_condones: false,
            friendly_dc: false,
            friendly_ile: false,
            friendly_infectologia: false,
            friendly_mac: false,
            friendly_prueba: false,
            friendly_ssr: false,
            friendly_vacunatorios: false,
            habilitado: false,
            horario_distrib: "De 8 a 18hs",
            horario_ile: "",
            horario_infectologia: "",
            horario_mac: "",
            horario_testeo: "",
            horario_vac: "",
            ile: false,
            latitude: 5,
            longitude: 10,
            mac: false,
            mail_distrib: "",
            mail_ile: "",
            mail_infectologia: "",
            mail_mac: "",
            mail_testeo: "",
            mail_vac: "",
            observacion: "",
            observaciones_testeo: "",
            pais: "",
            partido_comuna: "",
            piso_dpto: "",
            placeId: -1,
            provincia_region: "",
            prueba: false,
            responsable_distrib: "Caino Margarita",
            responsable_ile: "",
            responsable_infectologia: "",
            responsable_mac: "",
            responsable_testeo: "",
            responsable_vac: "",
            ssr: false,
            tel_distrib: "(02320) 480546",
            tel_ile: "",
            tel_infectologia: "",
            tel_mac: "",
            tel_testeo: "",
            tel_vac: "",
            tipo: "",
            ubicacion_distrib: "",
            ubicacion_ile: "",
            ubicacion_infectologia: "",
            ubicacion_mac: "",
            ubicacion_testeo: "",
            ubicacion_vac: "",
            web_distrib: "",
            web_ile: "",
            web_infectologia: "",
            web_mac: "",
            web_testeo: "",
            web_vac: ""
          }
        ],
        {
          latitude: -34.486068,
          longitude: -58.7250438
        }
      )
    ).toEqual([
      {
        altura: "sin número",
        aprobado: true,
        barrio_localidad: "Grand Bourg",
        calle: "Cabo Sosa",
        comentarios_distrib: "",
        comentarios_ile: "",
        comentarios_infectologia: "",
        comentarios_mac: "",
        comentarios_vac: "",
        condones: true,
        cruce: "El Callao",
        dc: false,
        establecimiento: "11 De Febrero",
        formattedAddress: "",
        friendly_condones: true,
        friendly_dc: false,
        friendly_ile: false,
        friendly_infectologia: false,
        friendly_mac: false,
        friendly_prueba: false,
        friendly_ssr: false,
        friendly_vacunatorios: false,
        habilitado: false,
        horario_distrib: "De 8 a 18hs",
        horario_ile: "",
        horario_infectologia: "",
        horario_mac: "",
        horario_testeo: "",
        horario_vac: "",
        ile: false,
        latitude: -34.486068,
        longitude: -58.7250438,
        mac: false,
        mail_distrib: "",
        mail_ile: "",
        mail_infectologia: "",
        mail_mac: "",
        mail_testeo: "",
        mail_vac: "",
        observacion: "",
        observaciones_testeo: "",
        pais: "",
        partido_comuna: "",
        piso_dpto: "",
        placeId: -1,
        provincia_region: "",
        prueba: false,
        responsable_distrib: "Caino Margarita",
        responsable_ile: "",
        responsable_infectologia: "",
        responsable_mac: "",
        responsable_testeo: "",
        responsable_vac: "",
        ssr: false,
        tel_distrib: "(02320) 480546",
        tel_ile: "",
        tel_infectologia: "",
        tel_mac: "",
        tel_testeo: "",
        tel_vac: "",
        tipo: "",
        ubicacion_distrib: "",
        ubicacion_ile: "",
        ubicacion_infectologia: "",
        ubicacion_mac: "",
        ubicacion_testeo: "",
        ubicacion_vac: "",
        web_distrib: "",
        web_ile: "",
        web_infectologia: "",
        web_mac: "",
        web_testeo: "",
        web_vac: ""
      }
    ]);
    expect(
      SearchEngine.teen(
        [
          {
            altura: "sin número",
            aprobado: true,
            barrio_localidad: "Grand Bourg",
            calle: "Cabo Sosa",
            comentarios_distrib: "",
            comentarios_ile: "",
            comentarios_infectologia: "",
            comentarios_mac: "",
            comentarios_vac: "",
            condones: true,
            cruce: "El Callao",
            dc: false,
            establecimiento: "11 De Febrero",
            formattedAddress: "",
            friendly_condones: false,
            friendly_dc: false,
            friendly_ile: false,
            friendly_infectologia: false,
            friendly_mac: false,
            friendly_prueba: false,
            friendly_ssr: false,
            friendly_vacunatorios: false,
            habilitado: false,
            horario_distrib: "De 8 a 18hs",
            horario_ile: "",
            horario_infectologia: "",
            horario_mac: "",
            horario_testeo: "",
            horario_vac: "",
            ile: false,
            latitude: -34.486068,
            longitude: -58.7250438,
            mac: false,
            mail_distrib: "",
            mail_ile: "",
            mail_infectologia: "",
            mail_mac: "",
            mail_testeo: "",
            mail_vac: "",
            observacion: "",
            observaciones_testeo: "",
            pais: "",
            partido_comuna: "",
            piso_dpto: "",
            placeId: -1,
            provincia_region: "",
            prueba: false,
            responsable_distrib: "Caino Margarita",
            responsable_ile: "",
            responsable_infectologia: "",
            responsable_mac: "",
            responsable_testeo: "",
            responsable_vac: "",
            ssr: false,
            tel_distrib: "(02320) 480546",
            tel_ile: "",
            tel_infectologia: "",
            tel_mac: "",
            tel_testeo: "",
            tel_vac: "",
            tipo: "",
            ubicacion_distrib: "",
            ubicacion_ile: "",
            ubicacion_infectologia: "",
            ubicacion_mac: "",
            ubicacion_testeo: "",
            ubicacion_vac: "",
            web_distrib: "",
            web_ile: "",
            web_infectologia: "",
            web_mac: "",
            web_testeo: "",
            web_vac: ""
          },
          {
            altura: "sin número",
            aprobado: true,
            barrio_localidad: "Grand Bourg",
            calle: "Cabo Sosa",
            comentarios_distrib: "",
            comentarios_ile: "",
            comentarios_infectologia: "",
            comentarios_mac: "",
            comentarios_vac: "",
            condones: true,
            cruce: "El Callao",
            dc: false,
            establecimiento: "11 De Febrero",
            formattedAddress: "",
            friendly_condones: false,
            friendly_dc: false,
            friendly_ile: false,
            friendly_infectologia: false,
            friendly_mac: false,
            friendly_prueba: false,
            friendly_ssr: false,
            friendly_vacunatorios: false,
            habilitado: false,
            horario_distrib: "De 8 a 18hs",
            horario_ile: "",
            horario_infectologia: "",
            horario_mac: "",
            horario_testeo: "",
            horario_vac: "",
            ile: false,
            latitude: 5,
            longitude: 10,
            mac: false,
            mail_distrib: "",
            mail_ile: "",
            mail_infectologia: "",
            mail_mac: "",
            mail_testeo: "",
            mail_vac: "",
            observacion: "",
            observaciones_testeo: "",
            pais: "",
            partido_comuna: "",
            piso_dpto: "",
            placeId: -1,
            provincia_region: "",
            prueba: false,
            responsable_distrib: "Caino Margarita",
            responsable_ile: "",
            responsable_infectologia: "",
            responsable_mac: "",
            responsable_testeo: "",
            responsable_vac: "",
            ssr: false,
            tel_distrib: "(02320) 480546",
            tel_ile: "",
            tel_infectologia: "",
            tel_mac: "",
            tel_testeo: "",
            tel_vac: "",
            tipo: "",
            ubicacion_distrib: "",
            ubicacion_ile: "",
            ubicacion_infectologia: "",
            ubicacion_mac: "",
            ubicacion_testeo: "",
            ubicacion_vac: "",
            web_distrib: "",
            web_ile: "",
            web_infectologia: "",
            web_mac: "",
            web_testeo: "",
            web_vac: ""
          }
        ],
        {
          latitude: -34.486068,
          longitude: -58.7250438
        }
      )
    ).toEqual([]);
  });
});
